
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 16 18:57:06 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 4;
  public static final int RELOP_GE = 41;
  public static final int CASE = 16;
  public static final int LPAREN = 32;
  public static final int SEMI = 28;
  public static final int CONTINUE = 13;
  public static final int FOR = 12;
  public static final int MINUS = 24;
  public static final int CHARACTER = 51;
  public static final int RPAREN = 33;
  public static final int AND = 18;
  public static final int RELOP_LT = 42;
  public static final int OR = 17;
  public static final int BOOL = 50;
  public static final int COMMA = 29;
  public static final int CLASS = 44;
  public static final int INC = 19;
  public static final int DIV = 22;
  public static final int PLUS = 20;
  public static final int ASSIGN = 26;
  public static final int IF = 10;
  public static final int THIS = 47;
  public static final int DOT = 30;
  public static final int ABSTRACT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int RELOP_LE = 43;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int NUMBER = 49;
  public static final int MOD = 23;
  public static final int IDENT = 48;
  public static final int BREAK = 14;
  public static final int VOID = 8;
  public static final int LBRACK = 36;
  public static final int SWITCH = 15;
  public static final int RELOP_EQ = 38;
  public static final int COLON = 27;
  public static final int LBRACE = 34;
  public static final int ELSE = 11;
  public static final int RBRACK = 37;
  public static final int ENUM = 3;
  public static final int READ = 5;
  public static final int RBRACE = 35;
  public static final int EXTENDS = 45;
  public static final int PROG = 2;
  public static final int QUESTION = 31;
  public static final int DEC = 25;
  public static final int PRINT = 6;
  public static final int RELOP_GT = 40;
  public static final int RELOP_NEQ = 39;
}

